# .github/workflows/deploy-swa.yml
name: Build & Deploy Contoso Real-Estate

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: swa-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4            # :contentReference[oaicite:2]{index=2}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # ---------- install front-end deps (with ci fallback) ----------
      - name: Install front-end deps
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found – using npm ci"
            npm ci
          else
            echo "No lock-file – using npm install"
            npm install
          fi

      - name: Build front-end
        run: npm run build --prefix frontend   # creates frontend/build

      # ---------- install API deps (same guard) ----------
      - name: Install API deps
        working-directory: api
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # ---------- deploy to Azure Static Web Apps ----------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1   # :contentReference[oaicite:3]{index=3}
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }}
          action: upload
          app_location: frontend/build
          api_location: api
          output_location: ""
