# .github/workflows/deploy-swa.yml
name: Build & Deploy Contoso Real-Estate

on:
  push:    { branches: [main] }
  workflow_dispatch:

permissions:
  contents: read
  id-token: write         # for future OIDC if you enable it

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: swa-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4            # GA checkout action :contentReference[oaicite:1]{index=1}
      - uses: actions/setup-node@v4          # GA node action :contentReference[oaicite:2]{index=2}
        with:
          node-version: 18

      # ---------- FRONT-END ----------
      - name: Install front-end deps
        run: |
          npm install --prefix src/frontend
      - name: Build front-end
        run: |
          npm run build --prefix src/frontend   # outputs to src/frontend/build

      # ---------- FUNCTIONS API ----------
      - name: Install API deps
        run: |
          npm install --prefix src/api

      # ---------- DEPLOY ----------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1   # official action :contentReference[oaicite:3]{index=3}
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }}
          action: upload
          app_location: "src/frontend/build"
          api_location: "src/api"
          output_location: ""
