name: Build & Deploy Contoso (explicit build)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      # ---------- FRONT-END ----------
      - name: Install FE deps (handles lock-file or no lock-file)
        run: |
          FE_DIR="src/frontend"     # <— CHANGE IF YOUR PATH DIFFERS
          if [ -f "$FE_DIR/package-lock.json" ]; then
            npm ci --prefix "$FE_DIR"
          else
            npm install --prefix "$FE_DIR"
          fi
      - name: Build FE
        run: npm run build --prefix src/frontend

      # ---------- API ----------
      - name: Install API deps
        run: |
          API_DIR="api"             # CHANGE if your Functions live elsewhere
          if [ -f "$API_DIR/package-lock.json" ]; then
            npm ci --prefix "$API_DIR"
          else
            npm install --prefix "$API_DIR"
          fi

      # ---------- DEPLOY ----------
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }}
          action: upload
          app_location: "src/frontend/build"   # must match the folder you built
          api_location: "api"
          output_location: ""
